### ISSUE TITLE
Emergency reconnect tests sometimes experience a double ISS

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#7994]
- Figure out why some emergency reconnect tests experience an additional ISS at round `r+1`
- #7992 will provide additional info
- Originally reported [here](https://github.com/swirlds/swirlds-platform-regression/issues/3586)

**Comment by alittley** [comment]
It appears that this issue was solved via https://github.com/hashgraph/hedera-services/pull/7977

- the bug was perfectly repeatable, but I can't reproduce after merging the above PR
- the second ISS was in the `events` field of `PlatformData`, and the above PR modifies event creation

This can be reopened if the problem is observed again

**Comment by alittley** [comment]
Reoccurrence on 8/23/23

http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230823-053624-GCP-Daily-ISS-4N/ISS-emergency-recovery-reconnect-1k-10m/

**Comment by alittley** [comment]
Another occurrence, on a different test, `ISS-emergency-recovery-1k-10m`

http://35.247.76.217:8095/alittley/08134-iss-catastrophic-failure/4N/ISS/20230823-174053-GCP-Daily-ISS-4N/ISS-emergency-recovery-1k-10m/node0000/

**Comment by alittley** [comment]
I believe the following is the reason behind the double ISS:

- A catastrophic ISS occurs
- 1 node doesn't detect the ISS and remains in `CHECKING`, since all other peers disconnect and shut down
- When the nodes come back online after the restart, they resume gossiping with the node that never shut down, and this causes the ISS

**Comment by alittley** [comment]
Closing since the expected fix merged. Reopen if this reoccurs

**Comment by edward-swirldslabs** [comment]
http://35.247.76.217:8095/swirlds-automation/develop/4N/ISS/20230905-061916-GCP-Daily-ISS-4N/ISS-emergency-recovery-reconnect-1k-10m/

Still occurring.

**Comment by cody-littley** [comment]
I'm going to close this under the theory that my recent fixes have resolved the problem. We can open a new issue if we see this again. Code pathways are so sufficiently different now that I don't think the logs from the old failures are relevant to the code in its current form.
